import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ChevronDown, ChevronRight, Printer } from 'lucide-react';
import PageHeading from '../components/ui/PageHeading';
import SectionHeader from '../components/ui/SectionHeader';
import StatusBadge from '../components/ui/StatusBadge';
import { evaluateRequirement, type EvaluationResult } from '../services/evaluationEngine';
import { getCurrentEvaluation, saveEvaluation } from '../services/storage';
import type { NewRequirementForm } from '../types';

const demoForm: NewRequirementForm = { material:'Coking Coal',quantity:'80000',tolerance:'5',consignments:'6',loadingCountry:'Australia',loadingPort:'Newcastle',dischargePort:'Paradip',preferredBerth:'COT Berth (Paradip)',requiredArrivalDate:'2026-11-15',planningPeriod:'H2 2026 (Jul – Dec)',monthlyRequirement:'80000',contractPreference:'Mixed arrangement',riskPreference:'Medium – balance cost and flexibility' };

function Summary({ result }: { result: EvaluationResult }) {
  const fields = [['Reference',result.reference],['Material',result.material],['Quantity',result.quantity],['Route',result.route],['Required arrival',result.requiredArrival],['Assessment date',result.assessmentDate]];
  return <div className="mb-5 flex flex-wrap gap-x-6 gap-y-2 rounded border border-border-base bg-white px-4 py-3">{fields.map(([label,value])=><div key={label} className="min-w-[130px]"><div className="text-2xs font-medium uppercase tracking-wide text-text-sub">{label}</div><div className="mt-0.5 text-sm font-medium">{value}</div></div>)}</div>;
}

export default function FinalRecommendation() {
  const navigate=useNavigate(); const [result]=useState(()=>getCurrentEvaluation()??evaluateRequirement(demoForm)); const [openId,setOpenId]=useState<string|null>(null); const [saved,setSaved]=useState(false);
  const riskColour=result.overallRisk==='High'?'text-risk':result.overallRisk==='Low'?'text-success':'text-warning';
  const keyFields=[['Recommended vessel class',result.recommendedVesselClass],['Booking position',result.bookingDecisionLabel],['Suitable booking period',result.suitableBookingPeriod],['Expected freight range',result.expectedFreightRangeLabel],['Port compatibility',result.portCompatibility],['Expected waiting time',`${result.expectedWaitingTimeHours} hours`],['Overall risk',result.overallRisk],['Forecast reliability',`${result.forecastReliabilityPct}%`]];
  return <div className="max-w-6xl"><PageHeading title="Final Recommendation" description="Traceable charter and procurement assessment based on the submitted requirement." actions={<><button className="flex items-center gap-1.5 rounded border border-border-base bg-white px-3 py-1.5 text-xs font-medium text-text-sub" onClick={()=>window.print()}><Printer size={13}/> Print</button><button disabled title="Planned for the next build" className="cursor-not-allowed rounded border border-border-base bg-white px-3 py-1.5 text-xs text-text-sub opacity-60">Export PDF — Coming next</button></>}/><Summary result={result}/>
  <div className="mb-5 overflow-hidden rounded border border-primary bg-white"><div className="bg-primary px-4 py-2 text-xs font-semibold uppercase tracking-wide text-white">Preliminary Recommendation</div><div className="grid grid-cols-2 sm:grid-cols-4">{keyFields.map(([label,value],i)=><div key={label} className={`border-b border-r border-border-base px-3 py-2.5 ${i===1?'font-semibold text-warning':''}`}><div className="mb-0.5 text-2xs font-medium uppercase tracking-wide text-text-sub">{label}</div><div className={`text-sm ${label==='Overall risk'?riskColour+' font-semibold':''}`}>{value}</div></div>)}</div><div className="border-t border-border-base bg-[#F8FAFB] px-4 py-3 text-xs leading-relaxed text-text-sub"><strong className="text-text-main">Note: </strong>{result.recommendationNote}</div></div>
  <div className="mb-5"><SectionHeader title="Vessel Class Comparison"/><div className="overflow-x-auto rounded border border-border-base bg-white"><table className="data-table w-full"><thead><tr>{['Vessel class','Capacity','Voyages','Cargo utilisation','Draft','Berth suitability','Estimated cost/MT','Evaluation'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{result.vesselEvaluations.map(v=><tr key={v.vesselClass} className={v.vesselClass===result.recommendedVesselClass?'bg-emerald-50':''}><td>{v.vesselClass}</td><td>{v.rangeLabel}</td><td>{v.voyagesRequired}</td><td>{v.voyagesRequired>1?'Split shipment':`${v.cargoUtilisationPct}%`}</td><td>{v.draftCompliant?'Complies':'Restricted'}</td><td title={v.berthNote}>{v.berthSuitable?'Suitable':v.berthNote}</td><td>${v.estimatedCostPerMT.toFixed(2)}</td><td><StatusBadge status={v.evaluation}/></td></tr>)}</tbody></table></div></div>
  <div className="mb-5"><SectionHeader title="Contract Arrangement Comparison"/><div className="overflow-x-auto rounded border border-border-base bg-white"><table className="data-table w-full"><thead><tr><th>Arrangement</th><th>Estimated cost</th><th>Exposure</th><th>Notes</th></tr></thead><tbody>{result.contract.options.map(o=><tr key={o.arrangement} className={o.arrangement.includes('recommended')?'bg-emerald-50':''}><td>{o.arrangement}</td><td>₹{o.estimatedCostCr} Cr</td><td><StatusBadge status={o.exposure}/></td><td>{o.notes}</td></tr>)}</tbody></table></div><div className="mt-3 rounded border border-border-base bg-white px-4 py-3"><div className="text-xs font-semibold uppercase tracking-wide text-text-sub">Suggested allocation</div><div className="my-3 flex flex-wrap gap-8">{[['6-month arrangement',result.contract.longTermPct],['3-month arrangement',result.contract.mediumTermPct],['Spot fixtures',result.contract.spotPct]].map(([label,pct])=><div key={String(label)}><div className="text-xs text-text-sub">{label}</div><strong>{pct}%</strong></div>)}</div><div className="rounded border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm font-medium text-success">Estimated saving compared with repeated spot fixtures: ₹{result.contract.savingVsAllSpotCr} Cr</div></div></div>
  <div className="mb-5"><SectionHeader title="Basis of Recommendation"/><div className="overflow-hidden rounded border border-border-base bg-white">{result.basisSections.map(s=><div key={s.id} className="border-b border-border-base last:border-0"><button className="flex w-full items-center justify-between px-4 py-2.5 text-left hover:bg-bg-page" onClick={()=>setOpenId(openId===s.id?null:s.id)}><span className="text-sm font-medium">{s.title}</span>{openId===s.id?<ChevronDown size={14}/>:<ChevronRight size={14}/>}</button>{openId===s.id&&<p className="px-4 pb-3 text-sm leading-relaxed text-text-sub">{s.body}</p>}</div>)}</div></div>
  <details className="mb-5 rounded border border-border-base bg-white"><summary className="cursor-pointer px-4 py-3 text-sm font-medium">Assessment information and data basis</summary><div className="border-t border-border-base px-4 py-3 text-xs leading-6 text-text-sub"><p>Freight rates: prototype historical market dataset • Vessel particulars: standard class specifications • Port constraints: berth-level prototype database • Weather and congestion: indicative demonstration values.</p><p>Production deployment requires licensed freight feeds, verified port data, AIS services and SAIL operational history. Assessment generated: {result.assessmentDateTime}.</p></div></details>
  <div className="flex items-center gap-3 pb-5"><button className="rounded border border-primary bg-primary px-4 py-1.5 text-sm font-medium text-white" onClick={()=>{saveEvaluation(result);setSaved(true)}}>Save Evaluation</button><button className="rounded border border-border-base bg-white px-4 py-1.5 text-sm" onClick={()=>navigate('/')}>Return to Overview</button>{saved&&<span className="text-xs font-medium text-success">Evaluation saved.</span>}</div></div>;
}
