import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import PageHeading from '../components/ui/PageHeading';
import SectionHeader from '../components/ui/SectionHeader';
import FreightTrendChart from '../components/charts/FreightTrendChart';
import StatusBadge from '../components/ui/StatusBadge';
import { berthDatabase } from '../data/berthData';
import { freightTrendData } from '../data/mockData';
import { getCurrentEvaluation, getSavedEvaluations } from '../services/storage';

const Shell=({title,description,children}:{title:string;description:string;children:React.ReactNode})=><div className="max-w-6xl"><PageHeading title={title} description={description}/>{children}</div>;
const Box=({title,children}:{title:string;children:React.ReactNode})=><section className="mb-5 rounded border border-border-base bg-white"><div className="border-b border-border-base px-4 py-2.5"><SectionHeader title={title}/></div><div className="p-4">{children}</div></section>;

export function FreightTrends(){return <Shell title="Freight Trend Assessment" description="Observed market movement and short-term rate indication for selected dry-bulk routes."><div className="mb-5 grid gap-3 sm:grid-cols-4">{[['Current indication','$28.10/MT'],['7-day estimate','$27.20/MT'],['15-day estimate','$25.90/MT'],['Assessment','Softening']].map(x=><div className="rounded border border-border-base bg-white p-4" key={x[0]}><div className="text-xs text-text-sub">{x[0]}</div><div className="mt-1 text-xl font-semibold">{x[1]}</div></div>)}</div><Box title="Newcastle–Paradip: Panamax / Supramax"><FreightTrendChart data={freightTrendData}/></Box><Box title="Planning Observation"><p className="text-sm leading-6 text-text-sub">Rates are expected to soften during the next two weeks before gradually recovering. Subject to the required-arrival buffer, review the requirement during 9–13 September 2026.</p><p className="mt-2 text-xs text-text-sub">Data basis: prototype historical market series. Production use requires a licensed freight feed.</p></Box></Shell>}

export function VesselEvaluationPage(){const r=getCurrentEvaluation();return <Shell title="Vessel Evaluation" description="Capacity, parcel utilisation and berth compliance for the current requirement.">{!r?<Empty/>:<Box title={`${r.quantity} • ${r.route}`}><div className="overflow-x-auto"><table className="data-table w-full"><thead><tr><th>Class</th><th>Typical DWT</th><th>Usable capacity</th><th>Voyages</th><th>Utilisation</th><th>Berth</th><th>Position</th></tr></thead><tbody>{r.vesselEvaluations.map(v=><tr key={v.vesselClass} className={v.vesselClass===r.recommendedVesselClass?'bg-emerald-50':''}><td>{v.vesselClass}</td><td>{v.typicalDwtMT.toLocaleString()} MT</td><td>{v.usableCapacityMT.toLocaleString()} MT</td><td>{v.voyagesRequired}</td><td>{v.voyagesRequired>1?'Split parcel':`${v.cargoUtilisationPct}%`}</td><td>{v.berthSuitable?'Suitable':'Restricted'}</td><td><StatusBadge status={v.evaluation}/></td></tr>)}</tbody></table></div></Box>}</Shell>}

export function PortBerthData(){return <Shell title="Port & Berth Data" description="Prototype operating limits used by the vessel compatibility check."><Box title="Berth Constraint Register"><div className="overflow-x-auto"><table className="data-table w-full"><thead><tr><th>Port</th><th>Berth</th><th>Max draft</th><th>Max LOA</th><th>Max beam</th><th>Typical wait</th><th>Operating note</th></tr></thead><tbody>{berthDatabase.filter(b=>b.port!=='Any').map(b=><tr key={b.berthKey}><td>{b.port}</td><td>{b.displayName}</td><td>{b.maxDraftM} m</td><td>{b.maxLoaM} m</td><td>{b.maxBeamM} m</td><td>{b.waitingHoursTypical} h</td><td>{b.notes}</td></tr>)}</tbody></table></div></Box><p className="text-xs text-text-sub">Prototype values must be replaced by verified port and terminal publications before operational use.</p></Shell>}

export function VoyageCost(){const r=getCurrentEvaluation();const selected=r?.vesselEvaluations.find(v=>v.vesselClass===r.recommendedVesselClass);const quantity=Number(r?.quantity.replace(/[^0-9]/g,''))||80000;const usd=selected?selected.estimatedCostPerMT*quantity:0;const rows=[['Basic freight',usd],['Port and handling provision',420000],['Expected waiting provision',10500],['Operational contingency',85000]];const total=rows.reduce((s,x)=>s+Number(x[1]),0);return <Shell title="Estimated Voyage Cost" description="Transparent cost build-up for the current vessel and route assessment.">{!r?<Empty/>:<><Box title={`${r.recommendedVesselClass} • ${r.route}`}><table className="data-table w-full"><thead><tr><th>Cost head</th><th>Basis</th><th>Estimated amount</th></tr></thead><tbody>{rows.map(([n,v],i)=><tr key={String(n)}><td>{n}</td><td>{i===0?`${quantity.toLocaleString()} MT × $${selected?.estimatedCostPerMT}/MT`:'Prototype planning provision'}</td><td>${Number(v).toLocaleString()}</td></tr>)}<tr className="bg-[#F4F6F8] font-semibold"><td>Estimated voyage total</td><td>Excluding cargo purchase value</td><td>${total.toLocaleString()}</td></tr></tbody></table></Box><p className="text-xs text-text-sub">Exchange rate, port tariff and demurrage assumptions remain configurable prototype inputs.</p></>}</Shell>}

export function ContractPlanning(){const r=getCurrentEvaluation();return <Shell title="Contract Planning" description="Cost and exposure comparison across spot, short-term and mixed arrangements.">{!r?<Empty/>:<><Box title="Arrangement Comparison"><div className="overflow-x-auto"><table className="data-table w-full"><thead><tr><th>Arrangement</th><th>Expected cost</th><th>Exposure</th><th>Planning note</th></tr></thead><tbody>{r.contract.options.map(o=><tr key={o.arrangement} className={o.arrangement.includes('recommended')?'bg-emerald-50':''}><td>{o.arrangement}</td><td>₹{o.estimatedCostCr} Cr</td><td><StatusBadge status={o.exposure}/></td><td>{o.notes}</td></tr>)}</tbody></table></div></Box><Box title="Suggested Cover"><div className="grid gap-4 sm:grid-cols-3">{[['6-month',r.contract.longTermPct],['3-month',r.contract.mediumTermPct],['Spot',r.contract.spotPct]].map(([n,p])=><div key={String(n)}><div className="text-xs text-text-sub">{n} arrangement</div><div className="mt-1 text-2xl font-semibold">{p}%</div></div>)}</div></Box></>}</Shell>}

export function AssumptionTesting(){const [fuel,setFuel]=useState(10);const [wait,setWait]=useState(24);const [supply,setSupply]=useState('Moderate');const base=130;const revised=useMemo(()=>Math.round((base+fuel*.12+Math.max(0,wait-14)*.04+(supply==='Low'?4:supply==='High'?-1:0))*10)/10,[fuel,wait,supply]);return <Shell title="Assumption Testing" description="Test how changes in fuel, waiting time and vessel supply affect the planning estimate."><Box title="Scenario Inputs"><div className="grid gap-5 sm:grid-cols-3"><label className="text-sm">Fuel-price adjustment (%)<input className="mt-1 w-full rounded border border-border-base px-3 py-2" type="number" value={fuel} onChange={e=>setFuel(Number(e.target.value))}/></label><label className="text-sm">Port waiting time (hours)<input className="mt-1 w-full rounded border border-border-base px-3 py-2" type="number" value={wait} onChange={e=>setWait(Number(e.target.value))}/></label><label className="text-sm">Vessel supply<select className="mt-1 w-full rounded border border-border-base px-3 py-2" value={supply} onChange={e=>setSupply(e.target.value)}><option>Low</option><option>Moderate</option><option>High</option></select></label></div></Box><Box title="Recalculated Position"><div className="grid gap-4 sm:grid-cols-3"><div><div className="text-xs text-text-sub">Base estimate</div><strong className="text-xl">₹{base} Cr</strong></div><div><div className="text-xs text-text-sub">Revised estimate</div><strong className="text-xl">₹{revised} Cr</strong></div><div><div className="text-xs text-text-sub">Change</div><strong className={revised>base?'text-risk text-xl':'text-success text-xl'}>{revised>base?'+':''}₹{(revised-base).toFixed(1)} Cr</strong></div></div><p className="mt-4 text-xs text-text-sub">Scenario values recalculate deterministically for demonstration; they are not live market observations.</p></Box></Shell>}

export function RiskRegister(){const risks=[['Panamax availability','Watch','Freight quotation may rise','Review within 48 hours'],['Paradip congestion','Moderate','12–18 hours waiting','Retain waiting provision'],['Bunker-price movement','Increasing','Higher voyage cost','Test +10% fuel case'],['Cyclone conditions','Low','Possible schedule interruption','Continue monitoring'],['Freight volatility','Moderate','Booking-price uncertainty','Retain partial contract cover']];return <Shell title="Risk Register" description="Current commercial and operational risks requiring planning attention."><Box title="Open Risks"><div className="overflow-x-auto"><table className="data-table w-full"><thead><tr><th>Risk</th><th>Status</th><th>Possible effect</th><th>Proposed response</th></tr></thead><tbody>{risks.map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td></tr>)}</tbody></table></div></Box></Shell>}

export function PreviousEvaluations(){const navigate=useNavigate();const rows=getSavedEvaluations();return <Shell title="Previous Evaluations" description="Locally saved charter assessments from this prototype session.">{rows.length===0?<Box title="Saved Evaluations"><p className="text-sm text-text-sub">No evaluations have been saved yet. Complete a requirement and select Save Evaluation.</p></Box>:<Box title="Saved Evaluations"><div className="overflow-x-auto"><table className="data-table w-full"><thead><tr><th>Reference</th><th>Material</th><th>Route</th><th>Quantity</th><th>Vessel</th><th>Booking position</th></tr></thead><tbody>{rows.map(r=><tr key={r.reference} className="cursor-pointer" onClick={()=>navigate(`/recommendation/${r.reference}`)}><td>{r.reference}</td><td>{r.material}</td><td>{r.route}</td><td>{r.quantity}</td><td>{r.recommendedVesselClass}</td><td>{r.bookingDecision}</td></tr>)}</tbody></table></div></Box>}</Shell>}

function Empty(){return <div className="rounded border border-border-base bg-white p-8 text-center"><p className="text-sm font-medium">No active requirement</p><p className="mt-1 text-xs text-text-sub">Create and evaluate a freight requirement to populate this module.</p></div>}
